-- CUDA 源文件直接由主目标 llaisys 编译，不再使用中间静态库。
-- 这样可以避免 __cudaRegisterLinkedBinary_* 符号被链接器丢弃的问题：
-- 当 CUDA 代码通过静态库(.a)链接进共享库(.so)时，Linux 链接器默认
-- 只引入被显式引用的符号，而 CUDA 的设备代码注册函数不会被 C++ 代码
-- 直接引用，因此会被丢弃。直接编译则不存在此问题。
--
-- 编译配置（cuflags 等）集中在 xmake.lua 的 llaisys 目标中。
